# Generated by Django 4.2.11 on 2024-04-18 10:43

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(default='profile_image_placeholder', max_length=255, verbose_name='image'),
        ),
    ]
