# Generated by Django 4.2.11 on 2024-04-18 11:08

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(default='profile_image_placeholder.png', max_length=255, verbose_name='image'),
        ),
    ]
