# Generated by Django 4.2.11 on 2024-04-17 09:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_alter_article_article_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='article',
            name='article_likes_count',
            field=models.BigIntegerField(default=0),
        ),
    ]
