# Generated by Django 4.2.11 on 2024-04-24 07:05

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_comment_comment_likes_comment_comment_likes_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='featured_article_image',
            field=cloudinary.models.CloudinaryField(default='placeholder.png', max_length=255, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='category',
            name='featured_category_image',
            field=cloudinary.models.CloudinaryField(default='placeholder.png', max_length=255, verbose_name='image'),
        ),
    ]
