# Generated by Django 4.2.11 on 2024-04-24 07:18

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_article_featured_article_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='featured_article_image',
            field=cloudinary.models.CloudinaryField(default='placeholder.jpeg', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='category',
            name='featured_category_image',
            field=cloudinary.models.CloudinaryField(default='placeholder.jpeg', max_length=255, verbose_name='image'),
        ),
    ]
